apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: ${NAME}
  name: ${NAME}
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: ${NAME}
    deploymentconfig: ${NAME}
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: ${NAME}
        deploymentconfig: ${NAME}
    spec:
      containers:
      - image: ${NAME}
        imagePullPolicy: Always
        name: ${NAME}
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        - containerPort: 8778
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - apicurio
      from:
        kind: ImageStreamTag
        name: apicurio:latest
        namespace: dev-tooling
      lastTriggeredImage: docker-registry.default.svc:5000/dev-tooling/apicurio@sha256:711175ca6333cf736c8fdf97c294b82060f0352513689c2174354cc585f754ad
    type: ImageChange