---
kind: Template
apiVersion: v1
metadata:
  name: service account
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: ${NAME}
parameters:
- name: NAME
  displayName: Name
  description: The name assigned to all objects and the resulting imagestream.
  required: true